name: coverage
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test --ci --maxWorkers=2

      - name: Comment Test Coverage
        uses: AthleticNet/comment-test-coverage@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/coverage-final.json
          title: Test Coverage